plugins {
    id 'java'
}

group = 'Dim_LJR'
version = '0.3-G'

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.21-R0.1-SNAPSHOT")
}

tasks.register('runPurpur', JavaExec) {
    dependsOn jar

    def serverJar = file("test/purpur-1.21.11-2568.jar")
    def runDir = file("run")

    classpath = files(serverJar)
    workingDir = runDir
    standardInput = System.in
    args("--nogui")

    // 每次启动前清理旧插件 + 复制新 jar
    doFirst {
        runDir.mkdirs()
        def pluginsDir = file("run/plugins")
        pluginsDir.mkdirs()
        // 删除旧版本的插件 jar
        delete fileTree(pluginsDir).matching { include "ArmsorPlus*.jar" }
        copy {
            from tasks.jar.archiveFile
            into pluginsDir
        }
    }
}

def targetJavaVersion = 21
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

tasks.register('reload') {
    dependsOn jar
    doLast {
        def pluginsDir = file("run/plugins")
        pluginsDir.mkdirs()
        // 删除旧版本插件 jar
        delete fileTree(pluginsDir).matching { include "ArmsorPlus*.jar" }
        copy {
            from tasks.jar.archiveFile
            into pluginsDir
        }
        println "已更新 run/plugins，在服务端输入指令重载插件"
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}
